name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: ./mvnw install -e -B -V
  test:
    name: Test
    needs: build
    strategy:
      matrix:
        java: ['8', '11', '17']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${matrix.java}
          distribution: 'temurin'
          cache: 'maven'
      - run: ./mvnw -f demo verify -e -B -V
    
